image: ubuntu

variables:
    DEPLOY_ENVIRONMENT:
        value: "staging"  # Deploy to staging by default
        description: "The deployment target. Change this variable to 'canary' or 'production' if needed."

cache:
    paths:
        - node_modules/

before_script:
    - apt-get update -qq
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - echo "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config

Test:
    script:
        - ssh -vvv -o PasswordAuthentication=no devel@bennyorder.com