image: ubuntu

before_script:
  - apt-get update -qq
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    
deploy_staging:
    script:
        - ssh devel@bennyorder.com "touch works.ciao"