image: alpine:latest

before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$DEVEL_OSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan bennyorder.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

build:
    variables: {}
    script:
        - ssh devel@bennyorder.com "hostname && echo 'Welcome!!!' > welcome.txt"
        