image: ubuntu

variables:
    DEPLOY_ENVIRONMENT:
        value: "staging"  # Deploy to staging by default
        description: "The deployment target. Change this variable to 'canary' or 'production' if needed."

    SSH_USER:
        value: "devel"
        description: "User used for developing stuff"

    SSH_SERVER_URI:
        value: "bennyorder.com"
        description: "BennyOrder developing server"

    URL:
        value: "bennyorder.com"
        description: "URL of the development server"

cache:
    paths:
        - node_modules/

before_script:
    - apt-get update -qq
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan bennyorder.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

Test:
    script:
        - ssh -o StrictHostKeyChecking=no devel@bennyorder.com
        