image: ubuntu

stages:
  - build

before_script:
  - apt-get update -qq
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

build:
  variables:
    COMMIT_TITLE: $CI_COMMIT_TITLE
  stage: build
  only:
    refs:
      - main
  script:
    - ssh devel@bennyorder.com "if [ ! -d \"/tmp/frontend\" ]; then git clone git@gitlab.com:bennyorder/developing/frontend.git; fi cd /tmp/frontend && rm -rf /tmp/frontend/build && git pull && yarn install && yarn build && cp -R /tmp/frontend/build/* /var/www/bennyorder && echo '[$(date)] $COMMIT_TITLE' >> /var/log/gitlab_deploy.log"
