image: ubuntu

stages:
  - pre-build
  - build
  - deploy
  - log
  - cleanup

before_script:
  - apt-get update -qq
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

pre-build:
  stage: pre-build
  only:
    refs:
      - main
  script:
    - ssh devel@bennyorder.com "mkdir -p /opt/bennyorder/frontend && cd /opt/bennyorder/frontend && rm -rf /opt/bennyorder/frontend/build && git pull && yarn install"

build:
  stage: build
  only:
    refs:
      - main
  script:
    - ssh devel@bennyorder.com "cd /opt/bennyorder/frontend && yarn build"

deploy:
  stage: deploy
  only:
    refs:
      - main
  script:
    - ssh devel@bennyorder.com "cp -R /opt/bennyorder/frontend/build/* /var/www/bennyorder"

log:
  variables:
    COMMIT_TITLE: $CI_COMMIT_TITLE
  stage: log
  only:
    refs:
      - main
  script:
    - ssh devel@bennyorder.com "echo '[$(date)] $COMMIT_TITLE' >> /var/log/gitlab_deploy.log"

cleanup:
  stage: cleanup
  only:
    refs:
      - main
  script:
    - ssh devel@bennyorder.com "rm -rf /opt/bennyorder"
